
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("address/save") ?>
<script>
function loadXMLDoc()
{
	var xmlhttp;
	if (window.XMLHttpRequest)
  	{// code for IE7+, Firefox, Chrome, Opera, Safari
    	xmlhttp=new XMLHttpRequest();
  	}
  	else
    {// code for IE6, IE5
	  xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
	xmlhttp.onreadystatechange=function()
    {
    	if (xmlhttp.readyState==4 && xmlhttp.status==200)
    	{
	    	document.getElementById("city").innerHTML=xmlhttp.responseText;
    	}
  	}
  	xmlhttp.open("GET","js/address.js",true);
  	xmlhttp.send();
}
</script>
<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("user/index", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit address</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="city">City</label>
        </td>
        <td align="left">
            <?php echo $this->tag->selectStatic(array("city", $CITY));?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="district">District</label>
        </td>
        <td align="left">
            <?php echo $this->tag->selectStatic(array("district", $DISTRICT));?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="zone">Zone</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("zone", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="building">Building</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("building", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="unit">Unit</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("unit", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="room">Room</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("room", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="remark">Remark</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("remark", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
