
<?php echo $this->tag->form("address/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("address", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create address</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="city">City</label>
        </td>
        <td align="left">
            <?php echo $this->tag->selectStatic(array("city", $CITY));?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="district">District</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("district", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="zone">Zone</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("zone", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="building">Building</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("building", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="unit">Unit</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("unit", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="room">Room</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("room", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="remark">Remark</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("remark", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
