
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("bill/new", "Create bill")) ?>
</div>

<?php echo $this->tag->form(array("bill/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search bill</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="bid">Bid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("bid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="bname">Bname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("bname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="gid">Gid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("gid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cost">Cost</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("cost", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="uid">Uid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("uid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="create_time">Create Of Time</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("create_time", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="finish_time">Finish Of Time</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("finish_time", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="place">Place</label>
        </td>
        <td align="left">
            <?php echo $this->tag->select(array("place", array("上地","北京"),'using'=>array('Bid'))) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
