
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("friend/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("friend", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit friend</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="uid">Uid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("uid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="fuid">Fuid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fuid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="friend_type">Friend Of Type</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("friend_type", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
