<?php use Phalcon\Tag; ?>

<?php echo $this->getContent() ?>

<ul class="nav nav-pills" role="tablist">
        <li role="presentation" ><a href="getAll">Friends<span class="badge"><?php echo count($page1); ?></span></a></li>
		<li role="presentation" class="active"><a href="getInvites">Invites<span class="badge"><?php echo count($page2); ?></span></a></li>
		<li role="presentation"><a href="getSends">Sends<span class="badge"><?php echo count($page3); ?></span></a></li>
</ul>
<div align="center">
    <?php echo $this->getContent(); ?>
</div>
<h3>Friends invites</h3>
<?php if(empty($page2)){ ?>
	<div class="alert alert-info" role="alert">
	      no invates.
    </div>
<?php }else{ ?>
<table class="browse" align="center">
    <thead>
        <tr>
            <th>Uid</th>
            <th>Fuid</th>
            <th>Friend_type</th>
            <th>Status</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page2->items as $friend) { ?>
        <tr>
            <td><?php echo $friend->uid ?></td>
            <td><?php echo $friend->fuid ?></td>
            <td><?php echo $friend->friend_type ?></td>
            <td><?php echo $friend->status ?></td>
            <td><?php echo $this->tag->linkTo(array("friend/accept/" . $friend->uid, "Accpet")); ?></td>
            <td><?php echo $this->tag->linkTo(array("friend/delete/" . $friend->uid, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("friend/getInvites", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("friend/getInvites?page2=" . $page2->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("friend/getInvites?page2=" . $page2->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("friend/getInvites?page2=" . $page2->last, "Last") ?></td>
                        <td><?php echo $page2->current, "/", $page2->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
<?php } ?>
