<?php use Phalcon\Tag; ?>

<?php echo $this->getContent() ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("friend/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("friend/search", "Find friends")); ?>
        </td>
    </tr>
</table>
<ul class="nav nav-pills" role="tablist">
        <li role="presentation" class="active"><a href="getAll">Friends<span class="badge"><?php echo count($page1); ?></span></a></li>
		<li role="presentation"><a href="getInvites">Invites<span class="badge"><?php echo count($page2); ?></span></a></li>
</ul>
<div align="center">
    <?php echo $this->getContent(); ?>
</div>
<h3>Friends</h3>
<?php if(empty($page1)){ ?>
	<div class="alert alert-info" role="alert">
	      no friends.
    </div>
<?php }else{ ?>
<table class="browse" align="center">
    <thead>
        <tr>
            <th>name</th>
            <th>uid</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page1->items as $friend) { ?>
        <tr>
            <td><?php echo $friend->name ?></td>
            <td><?php echo $friend->uid ?></td>
            <td><?php echo $this->tag->linkTo(array("friend/delete/" . $friend->uid, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("friend/index", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("friend/index?page1=" . $page1->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("friend/index?page1=" . $page1->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("friend/index?page1=" . $page1->last, "Last") ?></td>
                        <td><?php echo $page1->current, "/", $page1->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
<?php } ?>
