<?php echo $this->getContent() ?>
<div align="left">
<h2>User Info</h2>
<table class="table table-striped">
	<tbody>
		<tr><td>Name: <?php echo $user->uname;?></td></tr>
		<tr><td>Brithdy: <?php echo $user->birthday;?></td></tr>
	</tbody>
</table>
<h2>Address Info</h2>
			<?php if(empty($address)){
				echo $this->tag->linkTo(array("address/new", "edit address"));
			}else{
				echo $address->toArray();
			}?>
</div>
